### ISSUE TITLE
建议：可以根据author 、github的用户名来屏蔽不喜欢的作者

### ISSUE THREAD

**Issue by winter60** [zxkmm/siyuan_marketplace_blacklist#1]
### Feature request | 功能请求

rt.

**Comment by zxkmm** [comment]
谢谢，这个之后写，我在写ld246的屏蔽插件

**Comment by zxkmm** [comment]
刚看了下插件页面的html没有给插件作者的名字，但是github用户名应该可以做到，因为有repo链接

**Comment by winter60** [comment]
![image](https://github.com/user-attachments/assets/3413887d-11e4-46cb-b88b-7dd96e2e1084)

可以跟据 author 过滤出所有url

**Comment by zxkmm** [comment]
啊啊啊抱歉这个我有点不会写🫣🫣
我只会从html里面找元素

**Comment by winter60** [comment]
好的，github用户名更准确，怎么方便怎么来

**Comment by zxkmm** [comment]
17b3890a0ecafef903bb930d861b6ffbf1c42d35
